version: '3'

services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
        expose: 
            - "5095:5095"
            - "8080:8080"
            - "8081:8081"
            
    proxy:
        build:
            context: ./nginx
            dockerfile: ./Dockerfile
        ports:
            - "8050:8050"
        links:
            - app
        
        