version: '3'

services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
        expose:             
            - "8080:8080"          
            
    proxy:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - "8050:80"
        links:
            - app
        
        