version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - trade_statistics_network

  proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8050:80"
    links:
      - app
    networks:
      - trade_statistics_network

networks:
  trade_statistics_network:
    external: true
